name: App Center

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install node packages
      run: yarn install
    - name: build release
      run: cd android && ENVFILE=.env.production ./gradlew assembleRelease
    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1.2.1
      with:
        appName: mam17/Jintou
        token: f28febd4dfb740d9216c6b077407f4df6f72529f
        group: Testers
        file: android/app/build/outputs/apk/release/app-release.apk
        notifyTesters: true