name: AppCenter Action

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install node packages
      run: yarn install
    - name: build release
      run: cd android && ENVFILE=.env.production ./gradlew assembleRelease
    - name: upload artefact to App Center
      uses: wzieba/AppCenter-Github-Action@v1.2.1
      with:
        appName: mam17/Jintou
        token: ${{ secrets.APP_CENTER_TOKEN }}
        group: Internal
        file: android/app/build/outputs/apk/release/app-release.apk
        notifyTesters: true
    - name: Deploy to Codepush
      uses: NishanthShankar/codepush-action@master
      with:
        args: release-react -a mam17/Jintou -d Alpha
      env:
        APPCENTER_ACCESS_TOKEN: ${{ secrets.APP_CENTER_TOKEN }}